  function testcase() 
  {
    var accessed = false;
    function callbackfn(val, idx, obj) 
    {
      if (idx > 0)
      {
        accessed = true;
      }
      if (idx === 0)
      {
        throw new Error("Exception occurred in callbackfn");
      }
    }
    var obj = {
      0 : 11,
      4 : 10,
      10 : 8,
      length : 20
    };
    try
{      Array.prototype.map.call(obj, callbackfn);
      return false;}
    catch (ex)
{      return ex instanceof Error && ! accessed;}

  }
  {
    var __result1 = testcase();
    var __expect1 = true;
  }
  