  function testcase() 
  {
    var accessed = false;
    function callbackfn(val, idx, obj) 
    {
      if (idx > 1)
      {
        accessed = true;
      }
      return true;
    }
    var obj = {
      length : 20
    };
    Object.defineProperty(obj, "1", {
      get : (function () 
      {
        throw new RangeError("unhandle exception happened in getter");
      }),
      configurable : true
    });
    try
{      Array.prototype.some.call(obj, callbackfn);
      return false;}
    catch (ex)
{      return ex instanceof RangeError && ! accessed;}

  }
  {
    var __result1 = testcase();
    var __expect1 = true;
  }
  